server:
  port: 8081
spring:
  application:    name: User-Service  datasource:
    name: d2    url:   jdbc:mysql://localhost:3306/microservices_user_services 
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:    hibernate:      ddl-auto: update
    show-sql: true
    properties:      hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect  config:    import:
       configserver:http://localhost:8888#  profiles:#     active: dev     
#management:#  endpoint:#    health:#      show-details: always
##
#eureka:
#  instance:#    prefer-ip-address: true
#    
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url: 
#      default-zone: http://localhost:8761/eureka
          
          
      